DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS developer;

CREATE TABLE team (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(256) NOT NULL
);

CREATE TABLE developer (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  phone_number VARCHAR(256) NOT NULL,
  team_id BIGINT NOT NULL
);
